In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px
import faculty.datasets as datasets
from pandas.api.types import CategoricalDtype
import matplotlib.ticker as mtick
import statsmodels.api as sm


from pandas import Series, DataFrame
import os
from functools import reduce
vcvtype = 'nonrobust'

In [2]:
temdifference = pd.read_csv('/project/temdifference.csv')
all_football_18 = pd.read_csv('/project/all_football_18.csv')
market_value_all = pd.read_csv('/project/market_value_all.csv')
temdifference
market_value_all

    Unnamed: 0       Country  AvgTemperature  TemperatureDifference
0            0     Argentina        9.730419              -8.818761
1            1     Australia       11.830601              -6.718579
2            2       Belgium       19.479053               0.929872
3            3        Brazil       19.686096               1.136916
4            4      Colombia       13.899818              -4.649362
5            5    Costa Rica       22.836976               4.287796
6            6       Croatia       22.609290               4.060109
7            7       Denmark       18.753188               0.204007
8            8         Egypt       30.083789              11.534608
9            9        France       13.907559              -4.641621
10          10       Germany       18.722222               0.173042
11          11       Iceland        9.663934              -8.885246
12          12         Japan       23.262599               4.713418
13          13        Mexico       20.540680               1.991500
14          14       Morocco       20.108379               1.559199
15          15       Nigeria       28.053279               9.504098
16          16        Panama       26.645719               8.096539
17          17        Poland       20.906193               2.357013
18          18      Portugal       19.738616               1.189435
19          19        Russia       18.549180               0.000000
20          20  Saudi Arabia       37.094262              18.545082
21          21       Senegal       26.004554               7.455373
22          22   South Korea       24.826047               6.276867
23          23         Spain       22.928051               4.378871
24          24        Sweden       19.315118               0.765938
25          25   Switzerland       20.065877               1.516697
26          26       Tunisia       26.534608               7.985428
27          27       England       18.157559              -0.391621
28          28       Uruguay       10.268670              -8.280510
29          29          Peru       19.976250               1.427070
30          30          Iran       20.541000               1.991820
31          31        Serbia       12.843625              -5.705555

,Unnamed: 0,country,confederation,squad_size,avg_age,market_value_in_euros,market_value_digits,avg_market_value_of_players_in_mill_euros
0,0,Argentina,CONMEBOL,36,25.9,747.50 million,747,20.75
1,1,Australia,AFC,23,25.6,32.85 million,32,1.39
2,2,Belgium,UEFA,23,27.8,419.00 million,419,18.22
3,3,Brazil,CONMEBOL,23,26.5,870.50 million,870,37.83
4,4,Colombia,CONMEBOL,26,28.5,282.95 million,282,10.85
5,5,Costa Rica,CONCACAF,23,26.4,24.25 million,24,1.04
6,6,Croatia,UEFA,26,27.1,317.00 million,317,12.19
7,7,Denmark,UEFA,30,26.5,289.30 million,289,9.63
8,8,England,UEFA,25,25.4,1.23 billion,1000,40.00
9,9,France,UEFA,24,27.3,978.80 million,978,40.75
10,10,Germany,UEFA,21,27.5,572.00 million,572,27.24
11,11,Iran,AFC,27,27.4,61.13 million,61,2.26
12,12,Iceland,UEFA,23,28.7,23.25 million,23,1.00
13,13,Japan,AFC,28,27.7,118.10 million,118,4.21
14,14,Mexico,CONCACAF,23,28.7,214.00 million,214,9.30
15,15,Morocco,CAF,25,26.5,217.70 million,217,8.68
16,16,Nigeria,CAF,24,26.8,277.55 million,277,11.54
17,17,Peru,CONMEBOL,27,29.4,67.30 million,67,2.48
18,18,Poland,UEFA,26,27.3,292.80 million,292,11.23
19,19,Portugal,UEFA,23,27.3,775.00 million,775,33.70
20,20,Russia,UEFA,25,27.3,153.25 million,153,6.12
21,21,Saudi Arabia,AFC,23,25.2,26.25 million,26,1.13
22,22,Senegal,CAF,26,27.3,348.80 million,348,13.38
23,23,Serbia,UEFA,28,26.7,344.00 million,344,12.29
24,24,South Korea,AFC,25,27.2,127.95 million,127,5.08
25,25,Spain,UEFA,25,27.3,728.00 million,728,29.12
26,26,Sweden,UEFA,26,28.2,203.40 million,203,7.81
27,27,Switzerland,UEFA,22,26.8,189.20 million,189,8.59
28,28,Tunisia,CAF,33,26.2,39.18 million,39,1.18
29,29,Uruguay,CONMEBOL,27,27.4,263.20 million,263,9.74
30,30,Egypt,CAF,27,30.3,19.70 million,19,0.70
31,31,Panama,CONCACAF,23,28.4,10.17 million,10,0.43

In [3]:
# The final position of country teams should be included in dataset to act as the dependent variable
temdifference = temdifference.join(all_football_18['Final_positional_ranking'])
temdifference

,Unnamed: 0,Country,AvgTemperature,TemperatureDifference,Final_positional_ranking
0,0,Argentina,9.730419,-8.818761,16
1,1,Australia,11.830601,-6.718579,25
2,2,Belgium,19.479053,0.929872,3
3,3,Brazil,19.686096,1.136916,5
4,4,Colombia,13.899818,-4.649362,10
5,5,Costa Rica,22.836976,4.287796,30
6,6,Croatia,22.609290,4.060109,2
7,7,Denmark,18.753188,0.204007,13
8,8,Egypt,30.083789,11.534608,31
9,9,France,13.907559,-4.641621,4
10,10,Germany,18.722222,0.173042,1
11,11,Iceland,9.663934,-8.885246,23
12,12,Japan,23.262599,4.713418,27
13,13,Mexico,20.540680,1.991500,19
14,14,Morocco,20.108379,1.559199,15
15,15,Nigeria,28.053279,9.504098,9
16,16,Panama,26.645719,8.096539,24
17,17,Poland,20.906193,2.357013,22
18,18,Portugal,19.738616,1.189435,32
19,19,Russia,18.549180,0.000000,21
20,20,Saudi Arabia,37.094262,18.545082,26
21,21,Senegal,26.004554,7.455373,14
22,22,South Korea,24.826047,6.276867,7
23,23,Spain,22.928051,4.378871,29
24,24,Sweden,19.315118,0.765938,17
25,25,Switzerland,20.065877,1.516697,18
26,26,Tunisia,26.534608,7.985428,20
27,27,England,18.157559,-0.391621,12
28,28,Uruguay,10.268670,-8.280510,8
29,29,Peru,19.976250,1.427070,11
30,30,Iran,20.541000,1.991820,28
31,31,Serbia,12.843625,-5.705555,6

In [4]:
market_value_all = market_value_all.rename(columns = {"country":"Country"})
market_value_all
regression = pd.merge(temdifference, market_value_all, on = "Country", how = "left")
regression

,Unnamed: 0,Country,confederation,squad_size,avg_age,market_value_in_euros,market_value_digits,avg_market_value_of_players_in_mill_euros
0,0,Argentina,CONMEBOL,36,25.9,747.50 million,747,20.75
1,1,Australia,AFC,23,25.6,32.85 million,32,1.39
2,2,Belgium,UEFA,23,27.8,419.00 million,419,18.22
3,3,Brazil,CONMEBOL,23,26.5,870.50 million,870,37.83
4,4,Colombia,CONMEBOL,26,28.5,282.95 million,282,10.85
5,5,Costa Rica,CONCACAF,23,26.4,24.25 million,24,1.04
6,6,Croatia,UEFA,26,27.1,317.00 million,317,12.19
7,7,Denmark,UEFA,30,26.5,289.30 million,289,9.63
8,8,England,UEFA,25,25.4,1.23 billion,1000,40.00
9,9,France,UEFA,24,27.3,978.80 million,978,40.75
10,10,Germany,UEFA,21,27.5,572.00 million,572,27.24
11,11,Iran,AFC,27,27.4,61.13 million,61,2.26
12,12,Iceland,UEFA,23,28.7,23.25 million,23,1.00
13,13,Japan,AFC,28,27.7,118.10 million,118,4.21
14,14,Mexico,CONCACAF,23,28.7,214.00 million,214,9.30
15,15,Morocco,CAF,25,26.5,217.70 million,217,8.68
16,16,Nigeria,CAF,24,26.8,277.55 million,277,11.54
17,17,Peru,CONMEBOL,27,29.4,67.30 million,67,2.48
18,18,Poland,UEFA,26,27.3,292.80 million,292,11.23
19,19,Portugal,UEFA,23,27.3,775.00 million,775,33.70
20,20,Russia,UEFA,25,27.3,153.25 million,153,6.12
21,21,Saudi Arabia,AFC,23,25.2,26.25 million,26,1.13
22,22,Senegal,CAF,26,27.3,348.80 million,348,13.38
23,23,Serbia,UEFA,28,26.7,344.00 million,344,12.29
24,24,South Korea,AFC,25,27.2,127.95 million,127,5.08
25,25,Spain,UEFA,25,27.3,728.00 million,728,29.12
26,26,Sweden,UEFA,26,28.2,203.40 million,203,7.81
27,27,Switzerland,UEFA,22,26.8,189.20 million,189,8.59
28,28,Tunisia,CAF,33,26.2,39.18 million,39,1.18
29,29,Uruguay,CONMEBOL,27,27.4,263.20 million,263,9.74
30,30,Egypt,CAF,27,30.3,19.70 million,19,0.70
31,31,Panama,CONCACAF,23,28.4,10.17 million,10,0.43

,Unnamed: 0_x,Country,AvgTemperature,TemperatureDifference,Final_positional_ranking,Unnamed: 0_y,confederation,squad_size,avg_age,market_value_in_euros,market_value_digits,avg_market_value_of_players_in_mill_euros
0,0,Argentina,9.730419,-8.818761,16,0,CONMEBOL,36,25.9,747.50 million,747,20.75
1,1,Australia,11.830601,-6.718579,25,1,AFC,23,25.6,32.85 million,32,1.39
2,2,Belgium,19.479053,0.929872,3,2,UEFA,23,27.8,419.00 million,419,18.22
3,3,Brazil,19.686096,1.136916,5,3,CONMEBOL,23,26.5,870.50 million,870,37.83
4,4,Colombia,13.899818,-4.649362,10,4,CONMEBOL,26,28.5,282.95 million,282,10.85
5,5,Costa Rica,22.836976,4.287796,30,5,CONCACAF,23,26.4,24.25 million,24,1.04
6,6,Croatia,22.609290,4.060109,2,6,UEFA,26,27.1,317.00 million,317,12.19
7,7,Denmark,18.753188,0.204007,13,7,UEFA,30,26.5,289.30 million,289,9.63
8,8,Egypt,30.083789,11.534608,31,30,CAF,27,30.3,19.70 million,19,0.70
9,9,France,13.907559,-4.641621,4,9,UEFA,24,27.3,978.80 million,978,40.75
10,10,Germany,18.722222,0.173042,1,10,UEFA,21,27.5,572.00 million,572,27.24
11,11,Iceland,9.663934,-8.885246,23,12,UEFA,23,28.7,23.25 million,23,1.00
12,12,Japan,23.262599,4.713418,27,13,AFC,28,27.7,118.10 million,118,4.21
13,13,Mexico,20.540680,1.991500,19,14,CONCACAF,23,28.7,214.00 million,214,9.30
14,14,Morocco,20.108379,1.559199,15,15,CAF,25,26.5,217.70 million,217,8.68
15,15,Nigeria,28.053279,9.504098,9,16,CAF,24,26.8,277.55 million,277,11.54
16,16,Panama,26.645719,8.096539,24,31,CONCACAF,23,28.4,10.17 million,10,0.43
17,17,Poland,20.906193,2.357013,22,18,UEFA,26,27.3,292.80 million,292,11.23
18,18,Portugal,19.738616,1.189435,32,19,UEFA,23,27.3,775.00 million,775,33.70
19,19,Russia,18.549180,0.000000,21,20,UEFA,25,27.3,153.25 million,153,6.12
20,20,Saudi Arabia,37.094262,18.545082,26,21,AFC,23,25.2,26.25 million,26,1.13
21,21,Senegal,26.004554,7.455373,14,22,CAF,26,27.3,348.80 million,348,13.38
22,22,South Korea,24.826047,6.276867,7,24,AFC,25,27.2,127.95 million,127,5.08
23,23,Spain,22.928051,4.378871,29,25,UEFA,25,27.3,728.00 million,728,29.12
24,24,Sweden,19.315118,0.765938,17,26,UEFA,26,28.2,203.40 million,203,7.81
25,25,Switzerland,20.065877,1.516697,18,27,UEFA,22,26.8,189.20 million,189,8.59
26,26,Tunisia,26.534608,7.985428,20,28,CAF,33,26.2,39.18 million,39,1.18
27,27,England,18.157559,-0.391621,12,8,UEFA,25,25.4,1.23 billion,1000,40.00
28,28,Uruguay,10.268670,-8.280510,8,29,CONMEBOL,27,27.4,263.20 million,263,9.74
29,29,Peru,19.976250,1.427070,11,17,CONMEBOL,27,29.4,67.30 million,67,2.48
30,30,Iran,20.541000,1.991820,28,11,AFC,27,27.4,61.13 million,61,2.26
31,31,Serbia,12.843625,-5.705555,6,23,UEFA,28,26.7,344.00 million,344,12.29

In [6]:
X = regression[["TemperatureDifference", "avg_age", "avg_market_value_of_players_in_mill_euros"]] # independent variables
X = sm.add_constant(X)
Y = regression["Final_positional_ranking"] # dependent variable
model = sm.OLS(Y,X)
results = model.fit(cov_type=vcvtype)
print(results.summary())

                               OLS Regression Results
====================================================================================
Dep. Variable:     Final_positional_ranking   R-squared:                       0.184
Model:                                  OLS   Adj. R-squared:                  0.096
Method:                       Least Squares   F-statistic:                     2.098
Date:                      Mon, 13 Dec 2021   Prob (F-statistic):              0.123
Time:                              11:57:09   Log-Likelihood:                -113.29
No. Observations:                        32   AIC:                             234.6
Df Residuals:                            28   BIC:                             240.4
Df Model:                                 3
Covariance Type:                  nonrobust
=============================================================================================================
                                                coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------
const                                        20.3225     40.835      0.498      0.623     -63.323     103.968
TemperatureDifference                         0.3200      0.273      1.171      0.251      -0.240       0.880
avg_age                                      -0.0455      1.477     -0.031      0.976      -3.072       2.981
avg_market_value_of_players_in_mill_euros    -0.2499      0.141     -1.778      0.086      -0.538       0.038
==============================================================================
Omnibus:                        0.640   Durbin-Watson:                   2.175
Prob(Omnibus):                  0.726   Jarque-Bera (JB):                0.543
Skew:                           0.296   Prob(JB):                        0.762
Kurtosis:                       2.764   Cond. No.                         790.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

It can be seen that only average market value of players in each country team is statistically significant at 10% significance level. Holding anything else constant, increasing 1 million euros in average market value of team players would move the rank forward by 0.2499 on average.

It can be found that R-squared is quite low as well (i.e. 0.184) which means those independent variables put in the model did not explain the variation of the dependent variable (i.e. final ranking) very well. Also, the number of observations are for all variables are only 32, which is quite small.